### ISSUE TITLE
Hostname must match to Nextloud Website

### ISSUE THREAD

**Issue by Alex-C9ku** [matoH12/checkmk-nextcloud#2]
It seems that the checkmk hostname has to be the same as the Nextcloud Website. 
For example: Nextcloud website is "cloud.company.com" and the hostname in checkmk is "Server_123", then the check crashes with  "Error(MKFetcherError('Agent exited with code 1: Traceback...". 
Is there a way to get the check running without changing the hostname in checkmk?

**Comment by matoH12** [comment]
Yes, its possible, can you try updated version [nextcloud-1.2.2.mkp](https://github.com/matoH12/checkmk-nextcloud/blob/main/nextcloud-1.2.2.mkp) ?

**Comment by Alex-C9ku** [comment]
Version 1.2.2 works perfectly. Thank you!
