### ISSUE TITLE
Not working with port different from 443

### ISSUE THREAD

**Issue by Architecttheday** [matoH12/checkmk-nextcloud#3]
I have my Nextcloud Installation behind a Firewall / Router and the outside port is different from 443
When adding the service to my host it does not find anything
My attempt to add the port to agent_nextcloud_data line 112 enables connectivity and let me choose services, but activation fails when trying to enable services.

**Comment by matoH12** [comment]
Hi, try new version [nextcloud-1.2.3.mkp](https://github.com/matoH12/checkmk-nextcloud/blob/main/nextcloud-1.2.3.mkp) where you can define port.
